const theme = {
  colors: {
    primary: 'text-blue-300',
    secondary: 'text-teal-300',
    error: 'text-red-500',
    dark: 'text-gray-800',
    white: 'text-white',
    'soft-green': 'text-green-300',
    'soft-pink': 'text-pink-300',
    'pale-yellow': 'text-yellow-200',
    'vibrant-orange': 'text-orange-500',
    'intense-pink': 'text-pink-500',
    'light-gray': 'text-gray-300',
  },
  'background-colors': {
    primary: 'bg-blue-300',
    secondary: 'bg-teal-300',
    error: 'bg-red-500',
    dark: 'bg-gray-800',
    white: 'bg-white',
    'soft-green': 'bg-green-300',
    'soft-pink': 'bg-pink-300',
    'pale-yellow': 'bg-yellow-200',
    'vibrant-orange': 'bg-orange-500',
    'intense-pink': 'bg-pink-500',
    'light-gray': 'bg-gray-300',
  },
  'text-sizes': {
    sm: 'text-2xl',
    md: 'text-base',
    lg: 'text-lg',
    xl: 'text-xl',
    xxl: 'text-2xl',
    xxxl: 'text-3xl',
  },
  'padding-sizes': {
    sm: 'p-2',
    md: 'p-4',
    lg: 'p-6',
    xl: 'p-8',
    xxl: 'p-10',
    xxxl: 'p-12',
  },
  'button-sizes': {
    sm: 'py-2 px-4',
    md: 'py-4 px-6',
    lg: 'py-6 px-10',
  },
};

export default theme;
